async (page) => {
  page.setDefaultTimeout(6000);
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const check = (ok, message) => { if (!ok) throw new Error(message); };
  const frames = () => page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  const select = (id, value) => page.locator(`#qr-${id}`).selectOption(value);
  const entries = () => page.locator('#qr-context-panel .qr-list-entry');
  const entry = id => page.locator(`#qr-context-panel .qr-list-entry[data-review-id="${id}"]`);
  const scroll = () => page.evaluate(() => scrollY);
  const listScroll = () => page.locator('.qr-context-content').evaluate(el => el.scrollTop);
  const stationary = async (action, message) => {
    const position = () => page.locator('#reading-interval').evaluate(el => el.getBoundingClientRect().top);
    const y = await position();
    await action(); await frames();
    check(Math.abs(await position() - y) < 2, message + ` (${y} → ${await position()})`);
  };
  const recordState = () => page.locator('#quarto-review article').evaluateAll(items => items.map(i => [i.dataset.reviewId,i.dataset.status,i.dataset.author]));
  const assertMatches = async () => {
    const expected = await page.locator('#quarto-review article').evaluateAll(items => items.filter(i => !i.hidden).map(i => i.dataset.reviewId).sort());
    const actual = await entries().evaluateAll(items => items.map(i => i.dataset.reviewId).sort());
    check(JSON.stringify(expected) === JSON.stringify(actual), 'List does not contain exactly the filtered records');
  };
  const reports = [];
  for (const width of [1600,600,390]) {
    await page.setViewportSize({width,height:1000});
    await page.reload();
    await page.locator('#qr-author-hint').waitFor();
    await select('kind','');
    await select('status','');
    await page.locator('#reading-interval').evaluate(el => el.scrollIntoView({block:'center'})); await frames();
    await page.locator('#reading-interval').evaluate(el => { const line = Math.max(Math.min(innerHeight * .36,320), document.querySelector('#qr-controls').getBoundingClientRect().bottom + 16); scrollBy(0,el.getBoundingClientRect().top-line); }); await frames();
    const before = await recordState();
    await stationary(() => page.locator('#qr-show-list').click(), `${width}: opening list scrolled manuscript`);
    check(await page.locator('#qr-context-panel').isVisible(), `${width}: list unavailable`);
    check(await entries().count() === 59, `${width}: list omitted review records`);
    const colours = await entries().first().locator('summary').evaluate(el => ({summary:getComputedStyle(el).color,pane:getComputedStyle(document.querySelector('#qr-context-panel')).color}));
    check(colours.summary === colours.pane, 'List summary does not inherit readable theme colours');
    await assertMatches();
    const order = await entries().evaluateAll(items => items.map(i => i.dataset.reviewId));
    check(order.indexOf('c1') < order.indexOf('pending_word') && order.indexOf('pending_word') < order.indexOf('c2'), 'List is grouped by review type instead of manuscript order');
    check(order.indexOf('list_c2') < order.indexOf('list_c10'), 'List uses identifier sorting instead of passage order');
    await stationary(() => entry('c1').locator('summary').click(), `${width}: reading comment scrolled manuscript`);
    await entry('c1').locator('.qr-card').waitFor();
    check(await entry('c1').locator('.qr-body strong').first().innerText() === 'claim', 'Comment Markdown was lost');
    check((await entry('c1').innerText()).includes('The estimate is now qualified.'), 'Reply missing from list');
    check(await entry('c1').locator('a[data-qr-target]').count() === 0, 'Implicit navigation link remains inside list card');
    check(!(await entry('c1').locator('.qr-list-preview').innerText()).includes('strongmodest'), 'Passage preview concatenates alternatives');
    await stationary(() => entry('pending_word').locator('summary').click(), `${width}: reading change scrolled manuscript`);
    await entry('pending_word').locator('.qr-card').waitFor();
    check((await entry('pending_word').innerText()).includes('strong') && (await entry('pending_word').innerText()).includes('modest'), 'Change alternatives missing');
    await stationary(() => entry('list_c20').locator('summary').click(), `${width}: reading distant record scrolled manuscript`);
    await frames();
    const saved = await listScroll();
    check(saved > 200, 'List did not scroll independently');
    await stationary(() => page.locator('#qr-pane-passage').click(), `${width}: switching to passage scrolled manuscript`);
    await stationary(() => page.locator('#qr-show-list').click(), `${width}: returning to list scrolled manuscript`);
    check(Math.abs(await listScroll() - saved) < 3, `${width}: lost list position (${saved} → ${await listScroll()})`);
    check(await entry('list_c20').evaluate(el => el.open), 'Expanded entry was forgotten');
    await stationary(() => page.locator('#qr-next').click(), `${width}: Next navigated manuscript in list mode`);
    check(await page.evaluate(() => document.activeElement.matches('.qr-list-entry > summary')), 'List navigation lacks keyboard focus');
    await stationary(() => select('status','open-pending'), `${width}: status filter moved manuscript`);
    await assertMatches();
    check(await entries().count() === 52, 'Combined filter included decided records');
    await select('author','Example Author'); await assertMatches();
    check(await entries().count() === 25, 'Author filter mismatch (including reply authors)');
    await select('kind','comment'); await select('status','resolved'); await assertMatches();
    check(await entries().count() === 0, 'Empty filter produced entries');
    check((await page.locator('.qr-context-content').innerText()).includes('No review items match'), 'No-match explanation missing');
    await select('author',''); await select('kind',''); await select('status','');
    await stationary(() => page.locator('#qr-toggle-comments').click(), `${width}: hiding list moved manuscript`);
    check(!await page.locator('#qr-context-panel').isVisible(), 'Hidden list remains visible');
    await stationary(() => page.locator('#qr-toggle-comments').click(), `${width}: restoring list moved manuscript`);
    check(await page.locator('#qr-context-panel').isVisible(), 'List failed to restore');
    await page.locator('#qr-reading-view').click();
    check(!await page.locator('#qr-context-panel').isVisible(), 'List leaked into Reading view');
    await page.locator('#qr-restore-review').click();
    check(await page.locator('#qr-pane-list').getAttribute('aria-pressed') === 'true', 'Reading view lost list mode');
    for (const view of ['original','proposed','review']) { await select('view',view); await assertMatches(); }
    if (!await entry('list_c20').evaluate(el => el.open)) await entry('list_c20').locator('summary').click();
    const y = await scroll();
    await entry('list_c20').getByRole('button',{name:'Go to passage',exact:true}).click(); await frames();
    check(await page.locator('#qr-pane-passage').getAttribute('aria-pressed') === 'true', 'Go to passage did not switch view');
    check(Math.abs(await scroll()-y) > 100, 'Go to passage did not navigate');
    const location = await page.locator('#qr-anchor-list_c20').evaluate(el => el.getBoundingClientRect().top);
    check(location >= 0 && location < 1000, 'Requested passage is outside viewport');
    check(JSON.stringify(await recordState()) === JSON.stringify(before), 'Review decisions or attribution changed');
    const box = await page.locator('#qr-context-panel').boundingBox();
    if (box) check(box.x >= 0 && box.x+box.width <= width+1, 'Pane overflows viewport');
    reports.push(`${width}px`);
  }
  check(!errors.length, errors.join('; '));
  return `PASS: independent review list at ${reports.join(', ')}; all filtered items in manuscript order, discussion/replies and alternatives, independent scrolling and navigation, restored state, explicit passage navigation, hiding/Reading view, and unchanged review decisions.`;
}
